#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Choice {
    EveryPage,
    PicturesInside,
    Jpg,
    Png,
    SameAsPicture,
    A4,
    Letter,
    A3,
    A5,
    Legal,
    AsInWorkbook,
    ColumnsOnOnePage,
    SheetOnOnePage,
    ActualSize,
    AutoOrientation,
    Portrait,
    Landscape,
    NoMargin,
    SmallMargin,
    BigMargin,
    Colour,
    Grey,
    BlackAndWhite,
    AsTaken,
    Extreme,
    Recommended,
    Low,
    Drawn,
    Typed,
    FromPicture,
    BottomRight,
    BottomLeft,
    BottomCentre,
    TopRight,
    TopLeft,
    Centre,
    Black,
    White,
    HtmlReport,
    TextReport,
    Print,
    PrintHighQuality,
    Copy,
    Modify,
    Annotate,
    FillForms,
    Assemble,
}

impl Choice {
    pub const ALL: [Self; 47] = [
        Self::EveryPage,
        Self::PicturesInside,
        Self::Jpg,
        Self::Png,
        Self::SameAsPicture,
        Self::A4,
        Self::Letter,
        Self::A3,
        Self::A5,
        Self::Legal,
        Self::AsInWorkbook,
        Self::ColumnsOnOnePage,
        Self::SheetOnOnePage,
        Self::ActualSize,
        Self::AutoOrientation,
        Self::Portrait,
        Self::Landscape,
        Self::NoMargin,
        Self::SmallMargin,
        Self::BigMargin,
        Self::Colour,
        Self::Grey,
        Self::BlackAndWhite,
        Self::AsTaken,
        Self::Extreme,
        Self::Recommended,
        Self::Low,
        Self::Drawn,
        Self::Typed,
        Self::FromPicture,
        Self::BottomRight,
        Self::BottomLeft,
        Self::BottomCentre,
        Self::TopRight,
        Self::TopLeft,
        Self::Centre,
        Self::Black,
        Self::White,
        Self::HtmlReport,
        Self::TextReport,
        Self::Print,
        Self::PrintHighQuality,
        Self::Copy,
        Self::Modify,
        Self::Annotate,
        Self::FillForms,
        Self::Assemble,
    ];

    #[must_use]
    pub const fn value(self) -> &'static str {
        match self {
            Self::EveryPage => "pages",
            Self::PicturesInside => "extract",
            Self::Jpg => "jpg",
            Self::Png => "png",
            Self::SameAsPicture => "fit",
            Self::A4 => "a4",
            Self::Letter => "letter",
            Self::A3 => "a3",
            Self::A5 => "a5",
            Self::Legal => "legal",
            Self::AsInWorkbook => "",
            Self::ColumnsOnOnePage => "width",
            Self::SheetOnOnePage => "page",
            Self::ActualSize => "actual",
            Self::AutoOrientation => "auto",
            Self::Portrait => "portrait",
            Self::Landscape => "landscape",
            Self::NoMargin => "none",
            Self::SmallMargin => "small",
            Self::BigMargin => "big",
            Self::Colour => "colour",
            Self::Grey => "grey",
            Self::BlackAndWhite => "bw",
            Self::AsTaken => "original",
            Self::Extreme => "extreme",
            Self::Recommended => "recommended",
            Self::Low => "low",
            Self::Drawn => "draw",
            Self::Typed => "type",
            Self::FromPicture => "image",
            Self::BottomRight => "bottom-right",
            Self::BottomLeft => "bottom-left",
            Self::BottomCentre => "bottom-centre",
            Self::TopRight => "top-right",
            Self::TopLeft => "top-left",
            Self::Centre => "centre",
            Self::Black => "0,0,0",
            Self::White => "1,1,1",
            Self::HtmlReport => "html",
            Self::TextReport => "txt",
            Self::Print => "print",
            Self::PrintHighQuality => "print-high",
            Self::Copy => "copy",
            Self::Modify => "modify",
            Self::Annotate => "annotate",
            Self::FillForms => "forms",
            Self::Assemble => "assemble",
        }
    }
}
