#!/usr/bin/env python3
import sys
BIDI = ['L', 'R', 'AL', 'EN', 'ES', 'ET', 'AN', 'CS', 'NSM', 'BN', 'B', 'S', 'WS', 'ON', 'LRE', 'LRO', 'RLE', 'RLO', 'PDF', 'LRI', 'RLI', 'FSI', 'PDI']
JOIN = ['U', 'C', 'D', 'L', 'R', 'T']
FORMS = {'Iso': 0, 'Fin': 1, 'Init': 2, 'Med': 3}

def props_of(fields):
    out = {}
    for f in fields:
        if not f:
            continue
        if '=' in f:
            k, v = f.split('=', 1)
            out[k] = v
        elif f.startswith('-'):
            out[f[1:]] = False
        else:
            out[f] = True
    return out

def span(text):
    if '..' in text:
        a, b = text.split('..')
        return (int(a, 16), int(b, 16))
    return (int(text, 16), int(text, 16))

def main():
    path = sys.argv[1]
    version = '?'
    n = 1114112
    bc = bytearray(n)
    jt = bytearray(n)
    mirror = {}
    brackets = {}
    decomp = {}
    defaults = {}
    block = {}
    block_span = (-1, -1)
    for line in open(path, encoding='utf-8'):
        line = line.rstrip('\n')
        if not line or line.startswith('#'):
            continue
        fields = line.split(';')
        kind = fields[0]
        if kind == 'ucd':
            version = fields[1]
            continue
        if kind not in ('defaults', 'block', 'cp', 'unassigned'):
            continue
        lo, hi = span(fields[1])
        own = props_of(fields[2:])
        if kind == 'defaults':
            defaults = own
            props = own
        elif kind == 'block':
            block = {**defaults, **own}
            block_span = (lo, hi)
            props = block
        elif kind == 'unassigned':
            props = {**defaults, **own}
        else:
            base = block if block_span[0] <= lo <= block_span[1] else defaults
            props = {**base, **own}
        b = BIDI.index(props.get('bc', 'L'))
        j = JOIN.index(props.get('jt', 'U'))
        for cp in range(lo, hi + 1):
            bc[cp] = b
            jt[cp] = j
        if kind != 'cp':
            continue
        for cp in range(lo, hi + 1):
            if props.get('Bidi_M') is True and 'bmg' in own:
                mirror[cp] = int(own['bmg'], 16)
            if props.get('bpt', 'n') in ('o', 'c') and 'bpb' in props:
                brackets[cp] = (int(props['bpb'], 16), props['bpt'] == 'o')
            if 64336 <= cp <= 65279 and props.get('dt') in FORMS and ('dm' in own):
                decomp[cp] = (props['dt'], [int(x, 16) for x in own['dm'].split()])

    def runs(values):
        out = []
        last = None
        for cp in range(n):
            if values[cp] != last:
                out.append((cp, values[cp]))
                last = values[cp]
        return out
    w = sys.stdout.write
    w("// Generated by shared/pdf-canvas/unicode/generate.py from ICU's ppucd.txt\n")
    w(f'// (Unicode {version}). Do not edit by hand.\n\n')
    w('//! Unicode character data for the bidi algorithm and Arabic joining.\n\n')
    bidi_runs = runs(bc)
    w('/// Bidi_Class by range: each entry, `code point << 5 | class`, starts a\n')
    w("/// run of one class (an index into [`crate::bidi::Class`]'s order)\n")
    w('/// lasting until the next entry.\n')
    w(f'pub(crate) static BIDI_CLASS: [u32; {len(bidi_runs)}] = [\n')
    for cp, v in bidi_runs:
        w(f'    0x{cp << 5 | v:X},\n')
    w('];\n\n')
    joins = []
    for cp, v in runs(jt):
        if joins:
            joins[-1][1] = cp - 1
        joins.append([cp, n - 1, v])
    joins = [j for j in joins if JOIN[j[2]] in ('C', 'D', 'L', 'R')]
    w('/// Joining_Type C, D, L and R by range: first, last, type (1 C, 2 D,\n')
    w('/// 3 L, 4 R). Transparent characters are the marks (bidi class NSM)\n')
    w('/// and format characters (BN); everything else does not join.\n')
    w(f'pub(crate) static JOINING_TYPE: [(u32, u32, u8); {len(joins)}] = [\n')
    for a, b, v in joins:
        w(f'    (0x{a:X}, 0x{b:X}, {v}),\n')
    w('];\n\n')
    w('/// Bidi_Mirroring_Glyph: a character and its mirror image, by the first.\n')
    w(f'pub(crate) static MIRROR: [(u32, u32); {len(mirror)}] = [\n')
    for cp in sorted(mirror):
        w(f'    (0x{cp:X}, 0x{mirror[cp]:X}),\n')
    w('];\n\n')
    w('/// Bidi_Paired_Bracket: a bracket, its pair, and whether it opens.\n')
    w(f'pub(crate) static BRACKETS: [(u32, u32, bool); {len(brackets)}] = [\n')
    for cp in sorted(brackets):
        pair, opens = brackets[cp]
        w(f'    (0x{cp:X}, 0x{pair:X}, {('true' if opens else 'false')}),\n')
    w('];\n\n')
    letters = {}
    ligatures = {}
    for cp, (dt, dm) in decomp.items():
        if len(dm) == 1:
            letters.setdefault(dm[0], [0, 0, 0, 0])[FORMS[dt]] = cp
        elif len(dm) == 2 and 65269 <= cp <= 65276:
            ligatures.setdefault(dm[1], [0, 0])[FORMS[dt]] = cp
    w('/// Arabic Presentation Forms of a letter: isolated, final, initial,\n')
    w('/// medial (0 where Unicode has none).\n')
    w(f'pub(crate) static FORMS: [(u32, [u32; 4]); {len(letters)}] = [\n')
    for cp in sorted(letters):
        f = letters[cp]
        w(f'    (0x{cp:X}, [0x{f[0]:X}, 0x{f[1]:X}, 0x{f[2]:X}, 0x{f[3]:X}]),\n')
    w('];\n\n')
    w('/// Lam-alef ligatures in the Presentation Forms, by the alef: isolated\n')
    w('/// and final.\n')
    w(f'pub(crate) static LAM_ALEF: [(u32, [u32; 2]); {len(ligatures)}] = [\n')
    for cp in sorted(ligatures):
        f = ligatures[cp]
        w(f'    (0x{cp:X}, [0x{f[0]:X}, 0x{f[1]:X}]),\n')
    w('];\n')
main()
